# Generated by Django 4.0.6 on 2022-08-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='prefer_project_duration',
            field=models.CharField(blank=True, choices=[('short_term', 'Short term'), ('long_term', 'Long term')], default='short_term', max_length=10, null=True),
        ),
    ]
