# Generated by Django 4.0.6 on 2022-08-01 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_expert_prefer_project_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='citizenship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.citezenship'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='cv_file',
            field=models.FileField(default=1, upload_to='media/cv_files/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expert',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expert',
            name='first_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expert',
            name='last_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expert',
            name='phone',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expert',
            name='prefer_project_duration',
            field=models.CharField(choices=[('Short term', 'short_term'), ('Long term', 'long_term')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expert',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.sector'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expert',
            name='spoken_languages',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.language'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expert',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.title'),
            preserve_default=False,
        ),
    ]
